auto/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from auto.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.home, name="home"),
    
    path('backup/', views.backup, name="backup"),
    
    path('db/account/', UserList.as_view(), name='account-list'),
    path('db/account/create/', UserCreate.as_view(), name='account-create'),
    path('db/account/view/<int:pk>', UserView.as_view(), name='account-view'),
    path('db/account/update/<int:pk>', UserUpdate.as_view(), name='account-update'),
    
    path('db/omni/', OmniList.as_view(), name='omni-list'),
    path('db/omni/create/', OmniCreate.as_view(), name='omni-create'),
    path('db/omni/view/<int:pk>', OmniView.as_view(), name='omni-view'),
    path('db/omni/update/<int:pk>', OmniUpdate.as_view(), name='omni-update'),
    path('db/omni/inspect/<int:pk>', OmniInspect.as_view(), name='omni-inspect'),
    
    path('db/aux/', AuxList.as_view(), name='aux-list'),
    path('db/aux/view/<int:pk>', AuxView.as_view(), name='aux-view'),
    path('db/aux/update/<int:pk>', AuxUpdate.as_view(), name='aux-update'),
    
    path('db/ref/', RefList.as_view(), name='ref-list'),
    path('db/ref/create/', RefCreate.as_view(), name='ref-create'),
    path('db/ref/view/<int:pk>', RefView.as_view(), name='ref-view'),
    path('db/ref/update/<int:pk>', RefUpdate.as_view(), name='ref-update'),
    
    path('db/box/', BoxList.as_view(), name='box-list'),
    path('db/box/create/', BoxCreate.as_view(), name='box-create'),
    path('db/box/view/<int:pk>', BoxView.as_view(), name='box-view'),
    path('db/box/update/<int:pk>', BoxUpdate.as_view(), name='box-update'),
    
    path('db/sr/', SrList.as_view(), name='sr-list'),
    path('db/sr/create/', SrCreate.as_view(), name='sr-create'),
    path('db/sr/view/<int:pk>', SrView.as_view(), name='sr-view'),
    path('db/sr/update/<int:pk>', SrUpdate.as_view(), name='sr-update'),

    path('db/master/omnicell', OmniMaster.as_view(), name='omnimaster'),
    path('db/master/refrigerator', FlexMaster.as_view(), name='flexmaster'),
    path('db/master/lockbox', LockMaster.as_view(), name='lockmaster'),
    path('db/master/aux', AuxMaster.as_view(), name='auxmaster'),

    path('test/', TestView.as_view(), name='test'),

    path('dash/', DashView.as_view(), name='dash'),
    path('dash/omni/<int:pk>', OmniDashUpdate.as_view(), name="dash-omni"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('accounts/login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/', include('django.contrib.auth.urls')),
]

auto/models.py
from django.db import models
from django.db.models import Sum, Avg, Count, Min, Max
from django.contrib.auth.models import AbstractUser
from datetime import date, datetime, timedelta
from colorfield.fields import ColorField

class User(AbstractUser):
    Org = models.ForeignKey("Organization", on_delete=models.SET_NULL, blank=True, null=True)
    Theme = models.ForeignKey("Theme", on_delete=models.PROTECT, blank=True, null=True)

class Theme(models.Model):
    Name = models.CharField(max_length=50, blank=False, null=False)
    Header_BG = ColorField(default="#1d3557")
    Header_Txt = ColorField(default="#FFFFFF")
    Menu_BG = ColorField(default="#000000")
    Menu_Txt = ColorField(default="#FFFFFF")
    Search_BG = ColorField(default="#598baf")
    Search_Txt = ColorField(default="#FFFFFF")
    Content_BG = ColorField(default="#FFFFFF")
    Content_Txt = ColorField(default="#000000")
    Footer_BG = ColorField(default="#4d516d")
    Footer_Txt = ColorField(default="#000000")
    
    def __str__(self):
        return self.Name

class Omnicell(models.Model):
    """ Class for storing Omnicells """

    #Fields
    id = models.BigAutoField(primary_key=True)
    Org = models.ForeignKey("Organization", on_delete=models.SET_NULL, blank=True, null=True)
    Omni_Id = models.CharField(max_length=50, blank=True, null=True)
    Omni_Description = models.CharField(max_length=50, blank=True, null=True)
    Serial_Number = models.CharField(max_length=7, blank=True, null=True)
    Model = models.ForeignKey("OmnicellModel", on_delete=models.SET_NULL, blank=True, null=True)
    CT_Version = models.CharField(max_length=10, blank=True, null=True)
    PC_Name = models.CharField(max_length=20, blank=True, null=True)
    Ivanti = models.BooleanField(default=False)
    HD_Type = models.ForeignKey("HdType", on_delete=models.SET_NULL, blank=True, null=True)
    
    Site = models.ForeignKey("Site", on_delete=models.SET_NULL, blank=True, null=True)
    Building = models.ForeignKey("Building", on_delete=models.SET_NULL, blank=True, null=True)
    Area = models.CharField(max_length=10, blank=True, null=True)
    Room = models.CharField(max_length=10, blank=True, null=True)
    Door_Code = models.CharField(max_length=10, blank=True, null=True)
    Emergency = models.BooleanField(default=False)
    Note = models.TextField(max_length=500, blank=True, null=True)
    
    Port_Name = models.CharField(max_length=10, blank=True, null=True)
    Port_Location = models.ForeignKey("portLocation", on_delete=models.SET_NULL, blank=True, null=True)
    Boom = models.BooleanField(default=False)

    # Metadata
    class Meta:
        ordering = ['Omni_Id', 'Site', 'Building', 'Area']
    
    # Methods
    def __str__(self):
        return str(self.Omni_Id)

class HdType(models.Model):
    """Class Description"""

    #Fields
    id = models.BigAutoField(primary_key=True)
    Name = models.CharField(max_length=50, blank=True, null=True)

    # Metadata
    class Meta:
        ordering = ['id']
    
    # Methods
    def __str__(self):
        if self.Name:
            return self.Name
        else:
            return str(self.id)

class Aux(models.Model):
    """ Class for storing Aux Towers """

    #Fields
    id = models.BigAutoField(primary_key=True)
    Org = models.ForeignKey("Organization", on_delete=models.SET_NULL, blank=True, null=True)
    Omnicell = models.ForeignKey("Omnicell", on_delete=models.SET_NULL, blank=True, null=True)
    Serial_Number = models.CharField(max_length=7, blank=True, null=True)
    Model = models.ForeignKey("OmnicellModel", on_delete=models.SET_NULL, blank=True, null=True)   
    

    # Metadata
    class Meta:
        ordering = ['Omnicell', 'Model', 'Serial_Number']
    
    # Methods
    def __str__(self):
        return str(self.Model)

class Refrigerator(models.Model):
    """ Class for storing Refrigerators """

    #Fields
    id = models.BigAutoField(primary_key=True)
    Org = models.ForeignKey("Organization", on_delete=models.SET_NULL, blank=True, null=True)
    Facilities_Id = models.CharField(max_length=50, blank=True, null=True)
    Omnicell = models.ForeignKey("Omnicell", on_delete=models.SET_NULL, blank=True, null=True)
    Type = models.CharField(max_length=50, blank=True, null=True)
    Model = models.ForeignKey("RefrigeratorModel", on_delete=models.SET_NULL, blank=True, null=True)
    Wheels = models.BooleanField(default=False)
    Broken = models.BooleanField(default=False)

    # Metadata
    class Meta:
        ordering = ['Omnicell', 'Type', 'Facilities_Id']
    
    # Methods
    def __str__(self):
        return str(self.Omnicell) + " | " + str(self.Facilities_Id)

class OmnicellModel(models.Model):
    """Class for storing Omnicell Models """

    #Fields
    id = models.BigAutoField(primary_key=True)
    Generation = models.CharField(max_length=5, blank=True, null=True)
    Model = models.CharField(max_length=50, blank=True, null=True)

    # Metadata
    class Meta:
        ordering = ['Generation', 'Model']
    
    # Methods
    def __str__(self):
        return str(self.Generation+" "+self.Model)
    
class Site(models.Model):
    """ Class for storing Sites """

    #Fields
    id = models.BigAutoField(primary_key=True)
    Name = models.CharField(max_length=50, blank=True, null=True)

    # Metadata
    class Meta:
        ordering = ['Name']
    
    # Methods
    def __str__(self):
        if self.Name:
            return self.Name
        else:
            return str(self.id)
    
class Building(models.Model):
    """Class Description"""

    #Fields
    id = models.BigAutoField(primary_key=True)
    Name = models.CharField(max_length=50, blank=True, null=True)

    # Metadata
    class Meta:
        ordering = ['Name']
    
    # Methods
    def __str__(self):
        if self.Name:
            return self.Name
        else:
            return str(self.id)

class Lockbox(models.Model):
    """Class for storing lockboxes"""

    #Fields
    id = models.BigAutoField(primary_key=True)
    Refrigerator = models.ForeignKey("Refrigerator", on_delete=models.SET_NULL, blank=True, null=True)
    Key = models.CharField(max_length=10, blank=True, null=True)
    Medication = models.CharField(max_length=50, blank=True, null=True)
    Description = models.CharField(max_length=50, blank=True, null=True)

    # Metadata
    class Meta:
        ordering = ['Refrigerator']
    
    # Methods
    def __str__(self):
        return str(self.Refrigerator) + " | " + str(self.Medication)

class RefrigeratorModel(models.Model):
    """Class for storing refrigerator models"""

    #Fields
    id = models.BigAutoField(primary_key=True)
    Category = models.CharField(max_length=50, blank=True, null=True)
    ModelName = models.CharField(max_length=50, blank=True, null=True)
    Screen = models.BooleanField(default=False)
    Window = models.BooleanField(default=False)
    InteriorVolume = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=1)
    Height = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=1)
    Width = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=1)
    Depth = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=1)

    # Metadata
    class Meta:
        ordering = ['ModelName']
    
    # Methods
    def __str__(self):
        if self.ModelName:
            return self.ModelName
        else:
            return str(self.id)


class portLocation(models.Model):
    """Class for storing port locations"""

    #Fields
    id = models.BigAutoField(primary_key=True)
    Description = models.CharField(max_length=50, blank=True, null=True)

    # Metadata
    class Meta:
        ordering = ['id']
    
    # Methods
    def __str__(self):
        return self.Description
    
class Organization(models.Model):
    """Class for storing organizational groups"""

    #Fields
    id = models.BigAutoField(primary_key=True)
    Name = models.CharField(max_length=50, blank=True, null=True)

    # Metadata
    class Meta:
        ordering = ['id']
    
    # Methods
    def __str__(self):
        if self.Name:
            return self.Name
        else:
            return str(self.id)

class ServiceItem(models.Model):
    """Class Description"""

    #Fields
    id = models.BigAutoField(primary_key=True)
    Omnicell = models.ForeignKey("Omnicell", on_delete=models.SET_NULL, blank=True, null=True)
    Summary = models.CharField(max_length=100, blank=True, null=True)
    Note = models.TextField(max_length=500, blank=True, null=True)
    Solved = models.BooleanField(default=False)
    Opened =models.DateTimeField(blank=True, null=True)
    Opened_By = models.ForeignKey("User", on_delete=models.SET_NULL, blank=True, null=True, related_name='opener')
    Closed =models.DateTimeField(blank=True, null=True)
    Closed_By = models.ForeignKey("User", on_delete=models.SET_NULL, blank=True, null=True, related_name='closer')
    Ivanti_T = models.CharField(max_length=20, blank=True, null=True)
    Omni_T = models.CharField(max_length=20, blank=True, null=True)

    # Metadata
    class Meta:
        ordering = ['id']
    
    # Methods
    def __str__(self):
        return str(self.id)

# class theclass(models.Model):
#     """Class Description"""

#     #Fields
#     id = models.BigAutoField(primary_key=True)

#     # Metadata
#     class Meta:
#         ordering = ['id']
    
#     # Methods
#     def __str__(self):
#         return self.id

auto/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.fields import Field
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from auto.models import *

class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add custom attributes to fields, e.g., placeholders
        self.fields['new_password1'].widget.attrs['placeholder'] = 'New Password'
        self.fields['new_password2'].widget.attrs['placeholder'] = 'Confirm New Password'


class UserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + (
            'email',
            'first_name',
            'last_name',
            'is_staff'
        )

class UserEditForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
            'is_staff'
        )

class OmnicellCreateForm(ModelForm):
    class Meta:
        model = Omnicell
        fields = ['Omni_Id', 'Serial_Number', 'Omni_Description', 'Emergency', 'Model', 'CT_Version', 'PC_Name', 'Ivanti', 'Port_Name', 'Port_Location', 'Site', 'Building', 'Boom', 'Area', 'Room', 'Door_Code', 'Note', 'Org', 'HD_Type']
        widgets = {
            'Serial_Number': forms.TextInput(attrs={'class': 'inputField'}),
        }

class OmnicellForm(ModelForm):
    class Meta:
        model = Omnicell
        fields = ['Serial_Number', 'Omni_Description', 'Emergency', 'Model', 'CT_Version', 'PC_Name', 'Ivanti', 'Port_Name', 'Port_Location', 'Site', 'Building', 'Boom', 'Area', 'Room', 'Door_Code', 'Note', 'Org', 'HD_Type']
        widgets = {
            'Serial_Number': forms.TextInput(attrs={'class': 'inputField'}),
        }

class AuxForm(ModelForm):
    class Meta:
        model = Aux
        fields = ['Omnicell', 'Serial_Number', 'Model']

class LockboxForm(ModelForm):
    class Meta:
        model = Lockbox
        fields = ['Refrigerator', 'Medication', 'Key', 'Description']
        
class RefrigeratorCreateForm(ModelForm):
    class Meta:
        model = Refrigerator
        fields = ['Facilities_Id', 'Omnicell', 'Model', 'Org']
        widgets = {
            'Facilities_Id': forms.TextInput(attrs={'class': 'inputField'}),
        }

class RefrigeratorForm(ModelForm):
    class Meta:
        model = Refrigerator
        fields = ['Facilities_Id', 'Omnicell', 'Model', 'Org']
        widgets = {
            'Facilities_Id': forms.TextInput(attrs={'class': 'inputField'}),
        }
        
class ServiceItemForm(ModelForm):
    class Meta:
        model = ServiceItem
        fields = ('__all__')

auto/templates/db/omni/omni_create.html
{% extends 'base.html' %}

{% block menu %}
{% include 'menu/db/omni.html' %}
{% endblock %}

{% block form %}
<form method="post">
    {% csrf_token %}
{% endblock %}

{% block search %}

<a href="{% url 'omni-list' %}"><button type=button>
    Cancel
</button></a>

<button type=submit>Save</button>

{% endblock %}

{% block content %}

<div class="form-view">
    <span>
    {% if form.errors %}
        {% for field in form %}
            {% if field.errors %}
            <ul>
                {% for error in field.errors %}
                    <li>{{error}}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endfor %}
    {% endif %}
    </span>

    <h1>Hardware</h1>
    <span>
        <label for="id_Omni_Id">Omnicell ID:</label>
        {{form.Omni_Id}}
    </span>

    <span>
        <label for="id_Omni_Description">Description:</label>
        {{form.Omni_Description}}
    </span>

    <span>
        <label for="id_Serial_Number">Serial:</label>
        {{form.Serial_Number}}
    </span>

    <span>
        <label for="id_Model">Model:</label>
        {{form.Model}}
    </span>

    <h1>Location</h1>
    <span>
        <label for="id_Org">Organization:</label>
        {{form.Org}}
    </span>

    <span>
        <label for="id_Building">Building:</label>
        {{form.Building}}
    </span>

    <span>
        <label for="id_Area">Area:</label>
        {{form.Area}}
    </span>

    <span>
        <label for="id_Room">Room:</label>
        {{form.Room}}
    </span>

    <span>
        <label for="id_Door_Code">Door Code:</label>
        {{form.Door_Code}}
    </span>
        
    <h1>Software</h1>
    <span>
        <label for="id_CT_Version">CT Version:</label>
        {{form.CT_Version}}
    </span>

    <span>
        <label for="id_Ivanti">Ivanti:</label>
        {{form.Ivanti}}
    </span>

    <span>
        <label for="id_Note">Notes:</label>
        {{form.Note}}
    </span>


</div>


{% endblock %}

auto/templates/db/omni/omni_list.html
{% extends 'base.html' %}

{% block menu %}
{% include 'menu/db/omni.html' %}
{% endblock %}

{% block search %}
<a href="{% url 'omnimaster' %}"><button type=button class="master">
    Master Table
</button></a>

<span>
    <input name="q" type="search" class="search" placeholder="Search...">
    <button type=submit>Search</button>
</span>
{% endblock %}

{% block content %}

<div class="list">

<a class="new" href="{% url 'omni-create' %}"><button class="new" type=button>
    New Omnicell
</button></a>
{% for object in object_list %}

<a href="{% url 'omni-view' object.pk %}"><button type=button>
    {{object.Omni_Id}} | {{object.Omni_Description}}
</button></a>
        
{% endfor %}

</div>
{% endblock %}

auto/templates/db/omni/omni_table.html
{% extends 'base.html' %}

{% block menu %}

{% endblock %}

{% block content %}

    <div class="table">
        <table>
            <thead>
                <tr>
                    <td>{% now "F d, Y" %}</td>
                </tr>
                <tr>
                    <td>ID</td>
                    <td>Hospital</td>
                    <td>Area</td>
                    <td>Room</td>
                    <td>Serial Number</td>
                    <td>Description</td>
                    <td>Type</td>
                    <td>Model</td>
                    <td>Software Version</td>
                    <td>Computer Name</td>
                    <td>Notes</td>
                    <td>Emergency</td>
                    <td>Ivanti</td>
                    <td>Lockbox</td>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{object.Omni_Id}}</td>
                    <td>{{object.Building}}</td>
                    <td>{{object.Area}}</td>
                    <td>{{object.Room}}</td>
                    <td>{{object.Serial_Number}}</td>
                    <td>{{object.Omni_Description}}</td>
                    <td>{{object.Type}}</td>
                    <td>{{object.Model}}</td>
                    <td>{{object.CT_Version}}</td>
                    <td>{{object.PC_Name}}</td>
                    <td>{{object.Note}}</td>
                    <td>{{object.Emergency}}</td>
                    <td>{{object.Ivanti}}</td>
                    <td></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

auto/templates/db/omni/omni_update.html
{% extends 'base.html' %}

{% block menu %}
{% include 'menu/db/omni.html' %}
{% endblock %}

{% block form %}
<form method="post">
    {% csrf_token %}
{% endblock %}

{% block search %}
<a href="{% url 'omni-view' object.pk %}"><button type=button>
    Cancel
</button></a>
<button type=submit>Save</button>
{% endblock %}

{% block content %}
<div class="form-view">
    
    {% if form.errors %}
    <span>
        {% for field in form %}
            {% if field.errors %}
            <ul>
                {% for error in field.errors %}
                    <li>{{error}}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endfor %}
    </span>
    {% endif %}
    
    <h1>Hardware</h1>
    <span>
        <label for="id_Omni_Id">Omnicell ID:</label>
        <p>{{object.Omni_Id}}</p>
    </span>
 
    <span>
        <label for="id_Emergency">Emergency Omni:</label>
        {{form.Emergency}}
    </span>

    <span>
        <label for="id_Omni_Description">Description:</label>
        {{form.Omni_Description}}
    </span>

    <span>
        <label for="id_Serial_Number">Serial:</label>
        {{form.Serial_Number}}
    </span>

    <span>
        <label for="id_Model">Model:</label>
        {{form.Model}}
    </span>

    <h1>E-Box</h1>
    <span>
        <label for="id_CT_Version">CT Version:</label>
        {{form.CT_Version}}
    </span>

    <span>
        <label for="id_Ivanti">Ivanti:</label>
        {{form.Ivanti}}
    </span>

    <span>
        <label for="id_HD_Type">HD Type:</label>
        {{form.HD_Type}}
    </span>

    <h1>Notes</h1>
    <span>
        {{form.Note}}
    </span>

    <h1>Location</h1>
    <span>
        <label for="id_Org">Organization:</label>
        {{form.Org}}
    </span>

    <span>
        <label for="id_Building">Building:</label>
        {{form.Building}}
    </span>

    <span>
        <label for="id_Area">Area:</label>
        {{form.Area}}
    </span>

    <span>
        <label for="id_Room">Room:</label>
        {{form.Room}}
    </span>

    <span>
        <label for="id_Door_Code">Door Code:</label>
        {{form.Door_Code}}
    </span>
        
    


</div>
{% endblock %}

auto/templates/db/omni/omni_view.html
{% extends 'base.html' %}

{% block menu %}
{% include 'menu/db/omni.html' %}
{% endblock %}

{% block search %}
<a href="{% url 'omni-update' object.pk %}"><button type=button>
    Edit
</button></a>
{% endblock %}

{% block content %}
<div class="form-view">
    <h1>Omnicell Info</h1>
    <div class="grid">
        <div class="dash-box">
            <h1>Hardware</h1>
            <div class="content">
                <span>
                    <label for="id_Omni_Id">Omni ID:</label>
                    <p>{{object.Omni_Id}}</p>
                </span>

                <span>
                    <label for="id_Omni_Description">Description:</label>
                    <p>{{object.Omni_Description}}</p>
                </span>

                <span>
                    <label for="id_Serial_Number">Serial:</label>
                    <p>{{object.Serial_Number}}</p>
                </span>

                <span>
                    <label for="id_Model">Model:</label>
                    <p>{{object.Model}}</p>
                </span>
            </div>
        </div>

        {% if Auxs %}
        <div class="dash-box">
            <h1>Aux Units</h1>
            <div class="content">
                {% for Aux in Auxs %}              
                <a href="{% url 'aux-view' Aux.pk %}"><button type=button>
                    {{Aux.Serial_Number}}
                </button></a>      
                {% endfor %}
            </div>
        </div>
        {% endif %}

        <div class="dash-box">
            <h1>E-Box</h1>
            <div class="content">
                <span>
                    <label for="id_HD_Type">Drive Type:</label>
                    <p></p>
                </span>

                <span>
                    <label for="id_CT_Version">CT Version:</label>
                    <p>{{object.CT_Version}}</p>
                </span>

                <span>
                    <label for="id_Ivanti">Ivanti:</label>
                    <p>{% if object.Ivanti%}Yes{%else%}No{%endif%}</p>
                </span>

            </div>
        </div>

        <div class="dash-box">
            <h1>Location</h1>
            <div class="content">
                <span>
                    <label for="id_Building">Building:</label>
                    <p>{{object.Building}}</p>
                </span>

                <span>
                    <label for="id_Area">Area:</label>
                    <p>{{object.Area}}</p>
                </span>

                {% if object.Room %}
                <span>
                    <label for="id_Room">Room:</label>
                    <p>{{object.Room}}</p>
                </span>
                {% endif %}

                {% if object.Door_Code %}
                <span>
                    <label for="id_Door_Code">Door Code:</label>
                    <p>{{object.Door_Code}}</p>
                </span>
                {% endif %}
            </div>
        </div>

        {% if Refrigerators %}
        <div class="dash-box">
            <h1>Refrigerators</h1>
            <div class="content">
                {% for Refrigerator in Refrigerators %}
                <a href="{% url 'ref-view' Refrigerator.pk %}"><button type=button>
                    {{Refrigerator.Facilities_Id}} [{{Refrigerator.Type}}]
                </button></a>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        
        <div class="dash-box">
            <h1>Service Requests</h1>
            <div class="content">
                <a href="{% url 'sr-create' %}?o={{object.pk}}" class="new"><button type=button class="new">
                    NEW
                </button></a>
                {% for Request in Requests %}
                <a href="{% url 'sr-view' Request.pk %}"><button type=button>
                    {{Request.Summary}}
                </button></a>
                {% endfor %}
            </div>
        </div>

        <div class="dash-box">
            <h1>Service Log</h1>
            <div class="content">
            {% for Request in Logs %}
            <a href="{% url 'sr-view' Request.pk %}"><button type=button>
                {{Request.Summary}}
            </button></a>
            {% endfor %}
            </div>
        </div>

        {% if object.Note %}
        <div class="dash-box">
            <h1>Notes</h1>
            <div class="content">
                <span>
                <p>{{object.Note}}</p>
                </span>
            </div>
        </div>
        {% endif %}

    </div>
    
                          
</div>
{% endblock %}